spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc://mysql:/localhost:3306/simple-im
    username: root
    password: root
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 8888
logging:
  level:
    ROOT: info
